### ISSUE TITLE
Firebase uncaught exception crashing my node red on v1.1.1

### ISSUE THREAD

**Issue by sriramsv** [deldrid1/node-red-contrib-firebase#28]
```FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'length' of null


    at FirebaseOnce.<anonymous> (/data/node_modules/node-red-contrib-firebase/firebase/firebase_once.js:77:63)


    at c (/data/node_modules/firebase/lib/firebase-node.js:239:58)


    at /data/node_modules/firebase/lib/firebase-node.js:200:710


    at ec (/data/node_modules/firebase/lib/firebase-node.js:52:165)


    at ac (/data/node_modules/firebase/lib/firebase-node.js:31:216)


    at bc (/data/node_modules/firebase/lib/firebase-node.js:30:1259)


    at Ji.h.Ib (/data/node_modules/firebase/lib/firebase-node.js:219:287)


    at Rh.h.Jd (/data/node_modules/firebase/lib/firebase-node.js:186:251)


    at Fh.Jd (/data/node_modules/firebase/lib/firebase-node.js:176:364)


    at wh.Ig (/data/node_modules/firebase/lib/firebase-node.js:174:280)


    at zh (/data/node_modules/firebase/lib/firebase-node.js:168:464)


    at Client.Ka.onmessage (/data/node_modules/firebase/lib/firebase-node.js:167:321)


    at Client.dispatchEvent (/data/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)


    at Client._receiveMessage (/data/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)


    at Client.<anonymous> (/data/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)


    at emitOne (events.js:120:20)


    at Client.emit (events.js:210:7)


    at Client.<anonymous> (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)


    at pipe (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)


    at Pipeline._loop (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)


    at Pipeline.processIncomingMessage (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)


    at Extensions.processIncomingMessage (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20) 


11 Feb 10:03:29 - [red] Uncaught Exception:


11 Feb 10:03:29 - TypeError: Cannot read property 'length' of null


    at FirebaseOnce.<anonymous> (/data/node_modules/node-red-contrib-firebase/firebase/firebase_once.js:77:63)


    at c (/data/node_modules/firebase/lib/firebase-node.js:239:58)


    at /data/node_modules/firebase/lib/firebase-node.js:200:710


    at ec (/data/node_modules/firebase/lib/firebase-node.js:52:165)


    at ac (/data/node_modules/firebase/lib/firebase-node.js:31:216)


    at bc (/data/node_modules/firebase/lib/firebase-node.js:30:1259)


    at Ji.h.Ib (/data/node_modules/firebase/lib/firebase-node.js:219:287)


    at Rh.h.Jd (/data/node_modules/firebase/lib/firebase-node.js:186:251)


    at Fh.Jd (/data/node_modules/firebase/lib/firebase-node.js:176:364)


    at wh.Ig (/data/node_modules/firebase/lib/firebase-node.js:174:280)


    at zh (/data/node_modules/firebase/lib/firebase-node.js:168:464)


    at Client.Ka.onmessage (/data/node_modules/firebase/lib/firebase-node.js:167:321)


    at Client.dispatchEvent (/data/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)


    at Client._receiveMessage (/data/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)


    at Client.<anonymous> (/data/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)


    at emitOne (events.js:120:20)


    at Client.emit (events.js:210:7)


    at Client.<anonymous> (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)


    at pipe (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)


    at Pipeline._loop (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)


    at Pipeline.processIncomingMessage (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)


    at Extensions.processIncomingMessage (/data/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)```

**Comment by deldrid1** [comment]
Unfortunately, the version of the Firebase SDK used in this project is deprecated and no longer supported by Google (specifically the Auth restful endpoints I believe).

See the other issues -  I don’t have the bandwidth or motivation at this time to do the necessary updates (I haven’t touched Node-Red or Firebase in a couple of years at this point). 

Happy to review pull requests but otherwise I’m afraid you’re on your own for this one

**Comment by bigdoods** [comment]
@deldrid1 You should consider putting this notice in the README so that people are aware the project is no longer maintained.

Good luck!

**Comment by bourton88** [comment]
Is there a solution available for NodeRed? What package can be used?

**Comment by n0mer** [comment]
@bourton88 try this one: https://github.com/GoogleCloudPlatform/node-red-contrib-google-cloud/blob/master/firestore.js
